version: 2

run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - gosec
    - goconst
    - gocyclo
    - dupl
    - funlen
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocyclo
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0