name: Copilot Setup Steps

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  copilot-setup-steps:
    name: Setup Copilot Environment
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.3'
        check-latest: true
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
        
    - name: Install dependencies
      run: |
        npm ci
        npx playwright install --with-deps
      
    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.57.0
        golangci-lint --version
    
    - name: Install SQLite
      run: |
        sudo apt-get update
        sudo apt-get install -y sqlite3 libsqlite3-dev
        sqlite3 --version
    
    - name: Install Mockery (Go mock generator)
      run: |
        go install github.com/vektra/mockery/v2@latest
        mockery --version
    
    - name: Install Air (Go hot reload)
      run: |
        go install github.com/air-verse/air@latest
        air -v
    
    - name: Cache Go dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
